# Generated by Django 4.0.6 on 2022-07-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='High_level_tests',
        ),
    ]
